# Generated by Django 3.0.4 on 2020-05-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_register_model',
            fields=[
                ('model_username', models.CharField(max_length=30)),
                ('model_firstname', models.CharField(max_length=30)),
                ('model_lastname', models.CharField(max_length=30)),
                ('model_email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('model_phone', models.IntegerField(max_length=10)),
                ('model_password', models.CharField(max_length=30)),
            ],
        ),
    ]
